package utils

const (
	WINDOW_HEIGHT = 720
	WINDOW_WIDTH  = WINDOW_HEIGHT * 16 / 9
	ASPECT_RATIO  = float32(WINDOW_WIDTH) / float32(WINDOW_HEIGHT)

	CHUNK_SIZE      = 64
	CHUNK_FACE_AREA = CHUNK_SIZE * CHUNK_SIZE
	CHUNK_VOLUME    = CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE

	SQRT_3       = 1.7321
	CHUNK_RADIUS = (CHUNK_SIZE * SQRT_3) / 2

	EAST   = 0
	TOP    = 1
	SOUTH  = 2
	WEST   = 3
	BOTTOM = 4
	NORTH  = 5

	WORLD_SIZE = 11
)
